import React, { useState } from 'react';
import { FileText, Download, Filter, Calendar } from 'lucide-react';

const AdminReports = () => {
    const [reports] = useState([
        { id: 1, title: 'End of Month CDR Analysis - Oct', generatedBy: 'Officer John Doe', date: '2023-11-01', size: '2.4 MB' },
        { id: 2, title: 'Suspect Activity Report #992', generatedBy: 'Analyst Jane Smith', date: '2023-11-15', size: '1.1 MB' },
        { id: 3, title: 'System Usage Audit Report', generatedBy: 'System', date: '2023-11-20', size: '0.8 MB' },
        { id: 4, title: 'Criminal Database Summary', generatedBy: 'Admin', date: '2023-11-22', size: '5.6 MB' },
    ]);

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <h2 className="text-2xl font-bold text-gray-800">Generated Reports</h2>
                <div className="flex space-x-2">
                    <button className="flex items-center px-3 py-2 bg-white border border-gray-300 rounded-md text-gray-700 text-sm hover:bg-gray-50">
                        <Filter size={16} className="mr-2" />
                        Filter
                    </button>
                    <button className="flex items-center px-3 py-2 bg-white border border-gray-300 rounded-md text-gray-700 text-sm hover:bg-gray-50">
                        <Calendar size={16} className="mr-2" />
                        Date Range
                    </button>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {reports.map((report) => (
                    <div key={report.id} className="bg-white p-6 rounded-lg shadow-sm border border-gray-200 flex flex-col justify-between hover:shadow-md transition-shadow">
                        <div>
                            <div className="flex items-start justify-between mb-4">
                                <div className="p-3 bg-red-50 text-red-600 rounded-lg">
                                    <FileText size={24} />
                                </div>
                                <span className="text-xs text-gray-400 font-medium">{report.date}</span>
                            </div>
                            <h3 className="text-lg font-semibold text-gray-800 mb-1">{report.title}</h3>
                            <p className="text-sm text-gray-500 mb-4">Generated by {report.generatedBy}</p>
                        </div>

                        <div className="flex items-center justify-between pt-4 border-t border-gray-100 mt-2">
                            <span className="text-xs text-gray-400">{report.size}</span>
                            <button className="flex items-center text-sm font-medium text-blue-600 hover:text-blue-800 transition-colors">
                                <Download size={16} className="mr-1" />
                                Download PDF
                            </button>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
};

export default AdminReports;
